shop/admin/routes.py
import os
from flask import Blueprint, render_template, session, request, redirect, url_for, flash
from shop.admin.forms import RegistrationForm, LoginForm, ResetRequestForm, ChangePasswordForm
from shop import db, bcrypt, oauth, mail
from shop.admin.models import User
from shop.products.models import AddProduct, Brand, Category
from flask_login import login_required, current_user, login_user, logout_user
from flask_oauthlib.client import OAuthException
from flask_mail import Message
import mimetypes
from email.utils import make_msgid


admin = Blueprint("admin", __name__)


google = oauth.remote_app(
    'google',
    consumer_key='1059616331280-o192fo386aq3dpcac5lv51qjjkt0lvov.apps.googleusercontent.com',
    consumer_secret='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', 
    request_token_params={
        'scope': 'email',
    },
    base_url='https://www.googleapis.com/oauth2/v1/',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://accounts.google.com/o/oauth2/token',
)

@admin.route('/')
@login_required
def home():
    if 'email' not in session:
        flash("Please login first", 'danger')
        return redirect(url_for('admin.login'))
    products = AddProduct.query.all()
    return render_template('admin/index.html', title="Home Page", products=products)

@admin.route('/brands')
def brands():
    if 'email' not in session:
        flash("Please login first", 'danger')
        return redirect(url_for('admin.login'))
    brands = Brand.query.order_by(Brand.id.desc()).all()
    return render_template('admin/brand_category.html', title="Brand Page", brands=brands)

@admin.route('/category')
def category():
    if 'email' not in session:
        flash("Please login first", 'danger')
        return redirect(url_for('admin.login'))
    categories = Category.query.order_by(Category.id.desc()).all()
    return render_template('admin/brand_category.html', title="Category Page", categories=categories)

@admin.route('/login/google')
def login_google():
    return google.authorize(callback=url_for('admin.authorized_google', _external=True))

@admin.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm(request.form)
    if request.method == 'POST' and form.validate():
        # If no existing user, proceed to create a new user
        hash_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.name.data, username=form.username.data, email=form.email.data,
                    password=hash_password)
        try:
            db.session.add(user)
            db.session.commit()
            flash(f' Welcome {form.name.data} Thanks for registering', 'success')
            return redirect(url_for('admin.login'))
        except Exception as e:
            flash(f'User registration failed: {str(e)}', 'danger')
            return render_template('admin/register.html', form=form, title="Registration Page")

    return render_template('admin/register.html', form=form, title="Registration Page")

@admin.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin.home'))
    
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                session['email'] = form.email.data
                login_user(user)
                flash(f'Welcome, {form.email.data}! You have successfully logged in.', 'success')
                return redirect(request.args.get('next') or url_for('admin.home'))
            else:
                flash(" User does not exist.", 'danger')
                return render_template('admin/login.html', form=form, title="Login Page")
        except Exception as e:
            flash(f'User login failed: {str(e)}', 'danger')

    return render_template('admin/login.html', form=form, title="Login Page")

@admin.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('admin.login'))

@admin.route('/login/authorized_google')
def authorized_google():
    try:
        response = google.authorized_response()
        access_token = response.get('access_token')
        if response is None or access_token is None:
            print("Yes")
            flash('Access denied: reason={} error={}'.format(
                request.args['error_reason'],
                request.args['error_description']
            ), 'danger')
            return redirect(url_for('admin.login'))
    except OAuthException as e:
        print(f'OAuthException: {e}')

    session['google_token'] = (response['access_token'], '')
    user_info = google.get('userinfo', token=access_token)
    print("user_info", user_info)
    user = User.query.filter_by(email=user_info.data['email']).first()

    if user is None:
        # You might want to create a new user here if it doesn't exist
        flash('User not registered. Please register.', 'warning')
        return redirect(url_for('admin.register'))

    login_user(user)
    flash(f'Welcome, {user.email}! You have successfully logged in.', 'success')
    return redirect(request.args.get('next') or url_for('admin.home'))

def send_mail(user):
    token = user.get_token()
    reset_link = url_for('admin.reset_token', token=token, _external=True)

    subject = 'Password Reset Request'
    recipients = [user.email]
    sender = 'anurag.iitian07@gmail.com'

    # Create a MIMEMultipart message
    msg = Message(subject, recipients=recipients, sender=sender)
    html_body = f'''
        <p>To reset your password, please follow the link below:</p>
        <p><a href="{reset_link}">{reset_link}</a></p>
        <p>If you didn't send a password reset request, please ignore this message.</p>
    '''

    # Attach the image as an inline attachment
    img_path = 'D:\E-Shopper\Flask-Ecommerce-Store\shop\static\images\home\logo.png'
    mime_type, _ = mimetypes.guess_type(img_path)
    if mime_type:
        with open(img_path, 'rb') as img_file:
            try:
                msg.attach(filename='logo.png', data=img_file.read(), content_type=mime_type)
                # Set the Content-ID for the inline image
                img_cid = make_msgid(domain='example.com')[1:-1]
                html_body = html_body.replace('src="cid:logo"', f'src="cid:{img_cid}"')
            except AttributeError:
                # Handle the case where content_type is None or doesn't have split method
                pass

    msg.html = html_body
    mail.send(msg)

@admin.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = ResetRequestForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_mail(user)
            flash(f'Reset link has been sent. Check your email', 'success')
            return redirect(url_for('admin.login'))
    return render_template('admin/reset_password.html', title='Reset Password Page', form=form)

@admin.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    user = User.verify_token(token)
    if user is None:
        flash('That is invalid token. Please try again', 'warning')
        return redirect(url_for('admin.reset_password'))
    
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        hash_password = bcrypt.generate_password_hash(form.new_password1.data).decode('utf-8')
        user.password = hash_password
        db.session.commit()
        flash('Password changed successfully. Please Login', 'success')
        return redirect(url_for('admin.login'))
    return render_template('admin/change_password.html', title='Set Password Form', form=form)

shop/templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul  style="color: red;">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

shop/templates/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
            {% for category, message in messages %}
            <li class="alert alert-{{ category }}" id="msg" role="alert">
                {{ message }}
            </li>
            {% endfor %}
            </ul>
            <script type="text/javascript">
                window.setTimeout(function() {
                    $('#msg').fadeOut('slow');
                }, 2000); 
            </script>
        {% endif %}
{% endwith %}

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}Home | E-Shopper {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/bootstrap.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/style.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/font-awesome.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/prettyPhoto.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/price-range.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/animate.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/main.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static' ,filename='css/responsive.css')}}"
    />

    <link
      rel="shortcut icon"
      href="{{url_for('static', filename='images/ico/favicon.ico')}}"
    />
    <link
      rel="apple-touch-icon-precomposed"
      sizes="144x144"
      href="{{url_for('static', filename='images/ico/apple-touch-icon-144-precomposed.png')}}"
    />
    <link
      rel="apple-touch-icon-precomposed"
      sizes="114x114"
      href="{{url_for('static', filename='images/ico/apple-touch-icon-114-precomposed.png')}}"
    />
    <link
      rel="apple-touch-icon-precomposed"
      sizes="72x72"
      href="{{url_for('static', filename='images/ico/apple-touch-icon-72-precomposed.png')}}"
    />
    <link
      rel="apple-touch-icon-precomposed"
      href="{{url_for('static', filename='images/ico/apple-touch-icon-57-precomposed.png')}}"
    />
  </head>
  <!--/head-->

  <body>
    <header id="header">
      <div class="header-middle">
        <!--/header_top-->
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="logo pull-left">
                <a href="admin/index.html"
                  ><img src="{{url_for('static', filename='images/home/logo.png')}}" alt=""
                /></a>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="shop-menu pull-right">
                <ul class="nav nav-pills">
                  {% block nav3 %}
                  <li>
                    <a href="#"><i class="fa fa-user"></i>Account</a>
                  </li>
                  {% endblock nav3 %}
                  <li>
                    <a href="#"><i class="fa fa-heart"></i> Wishlist</a>
                  </li>
                  <li>
                    <a href="#"><i class="fa fa-crosshairs"></i> Checkout</a>
                  </li>
                  {% block nav4 %}{% endblock nav4 %} {% block nav1 %}{%
                  endblock nav1 %} {% block nav %}{% endblock nav %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--/header-middle-->

      <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
          <div class="row">
            <div class="col-sm-9">
              <div class="navbar-header">
                <button
                  type="button"
                  class="navbar-toggle"
                  data-toggle="collapse"
                  data-target=".navbar-collapse"
                >
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="mainmenu pull-left">
                <ul class="nav navbar-nav collapse navbar-collapse">
                  <li><a href="#" class="active">Home</a></li>
                  {% if request.endpoint != 'admin.reset_password' %}
                  <li class="dropdown">
                    <a href="#">Shop<i class="fa fa-angle-down"></i></a>
                    <ul role="menu" class="sub-menu">
                      <li><a href="{{url_for('admin.home')}}">Products</a></li>
                      <li><a href="#">Cart</a></li>
                      {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('admin.logout') }}">Logout</a></li>
                      {% else %}
                        <li><a href="{{ url_for('admin.login') }}">Login</a></li>
                      {% endif %}
                    </ul>
                  </li>
                  {% endif %}
                  <li><a href="#">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--/header-bottom-->
    </header>
    <!--/header-->
    {% block content %}  {% endblock content %} {%
    block js %} {% endblock js %}

    <footer id="footer">
      <!--Footer-->
      <div class="footer-widget">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="companyinfo">
                <h2><span>e</span>-shopper</h2>
                <p>
                  "E-SHOPPER is a Flask-based E-commerce Store, designed to
                  provide a robust and customizable platform for online
                  shopping"
                </p>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-widget">
                <h2>Service</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li><a href="#">Contact Us</a></li>
                  <li><a href="#">Order Status</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-widget">
                <h2>Subscribe to Our Newsletter</h2>
                <form action="#" method="post" class="searchform">
                  <input
                    type="text"
                    name="email"
                    placeholder="Your email address"
                  />
                  <button type="submit" class="btn btn-default">
                    <i class="fa fa-arrow-circle-o-right"></i>
                  </button>
                  <p>
                    Stay informed with the latest updates from our site.
                    Subscribe now to receive regular notifications.
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="footer-bottom">
        <div class="container">
          <div class="row">
            <p class="pull-left">
              Copyright © 2023 E-SHOPPER Inc. All rights reserved.
            </p>
            <p class="pull-right">
              Designed by
              <span
                ><a target="_blank" href="http://www.themeum.com"
                  >Anurag</a
                ></span
              >
            </p>
          </div>
        </div>
      </div>
    </footer>
    <!--/Footer-->

    <script src="{{url_for('static', filename='js/jquery.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/jquery.scrollUp.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/price-range.js')}}"></script>
    <script src="{{url_for('static', filename='js/jquery.prettyPhoto.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
    <script src="{{url_for('static', filename='js/cart.js')}}"></script>
  </body>
</html>